name: Bun Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Bun Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run Bun test
      - name: Run tests
        run: bun test

  build:
    name: Bun Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run Bun build
      - name: Build
        run: bun build
